### ISSUE TITLE
QuillToolbar.basic() property "fontSizeValues" => exception

### ISSUE THREAD

**Issue by accvi** [VisualSystemsCorp/vsc_quill_delta_to_html#1]
Hi, I tried to set the following property in QuillToolbar.basic():

fontSizeValues: const {
    "Small": "8",
    "Medium": "24.5",
    "Large": "46",
    "Clear": "0"
  }),

This gives me the following exception:

VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'double' is not a subtype of type 'String?'
#0      OpAttributes.size
op_attribute_sanitizer.dart:76
#1      OpAttributeSanitizer.sanitize
op_attribute_sanitizer.dart:227
#2      InsertOpsConverter.convert
insert_ops_converter.dart:40
#3      QuillDeltaToHtmlConverter.getGroupedOps
quill_delta_to_html_converter.dart:124
#4      QuillDeltaToHtmlConverter.convert

Is there a workaround or am I doing something wrong?

**Comment by dsyrstad** [comment]
Can you please provide the quill Delta ops that you're providing to  QuillDeltaToHtmlConverter? 

Font sizes are typically symbolic names, hence strings - e.g., `'large'` or `'20px'`. I'm not sure how flutter_quill is going from your strings to doubles.

**Comment by dsyrstad** [comment]
@accvi I have changed this to handle strings and numerics for `size` and `width` attributes. It is in version 1.0.2. However, with your font sizes, you will have to provide additional converter options so the HTML produces corresponding font sizes. Something like:

```dart
      ConverterOptions(
        converterOptions: OpConverterOptions(
          inlineStylesFlag: true,
          inlineStyles: InlineStyles({
            ...defaultInlineStyles.attrs,
            'size': InlineStyleType(map: {
              '8': 'font-size: 8px',
              '24.5': 'font-size: 24.5px',
              '46': 'font-size: 46px',
            }),
          }),
        ),
      ),
```
