### ISSUE TITLE
Color attribute create nested <p> in a single line

### ISSUE THREAD

**Issue by CatHood0** [VisualSystemsCorp/vsc_quill_delta_to_html#10]
I found a "error" (is only a error for me, because i need different transformation of that attributes), when there are color attributes between spaces, and, if after the color attribute, comes a space or word, without attributes, the converter transform it in something like:

This delta:

```dart
   {"insert":"colored word","attributes":{"color":"rgb(239,39,4)"},{"insert":" word"},{"insert":"another colored word","attributes":{"color":"rgb(239,39,4)"}
```
Is transformed to ->
```HTML
<p><p style="color:rgb(239,39,4)">colored word</p> word<p style="color:rgb(239,39,4)">another colored word</p></p>
```
**That is complex to analyze**, then i prefer something as this HTML: 
```HTML
<p style="color:rgb(239,39,4)">colored word</p><p> word</p><p style="color:rgb(239,39,4)">another colored word</p>
``` 
or adding `span` tag instead of `p` tag:
```HTML
<span style="color:rgb(239,39,4)">colored word</span><p> word</p><span style="color:rgb(239,39,4)">another colored word</span>
```

How could i change it? This just happens with **colors attribute**

**Comment by dsyrstad** [comment]
@CatHood0 I get different results using your delta JSON (which I had to make corrections to):
```json
[
  {
    "insert": "colored word",
    "attributes": {
      "color": "rgb(239,39,4)"
    }
  },
  {
    "insert": " word"
  },
  {
    "insert": "another colored word",
    "attributes": {
      "color": "rgb(239,39,4)"
    }
  }
]
```
Which gives me:
```html
<p><span style="color:rgb(239,39,4)">colored word</span> word<span style="color:rgb(239,39,4)">another colored word</span></p>
```
This is using `span`. The converter options I used were:
```dart
QuillDeltaToHtmlConverter(
    deltaJson,
    ConverterOptions.forEmail(),
  )
```

**Comment by CatHood0** [comment]
I think it could be my version (i modified some parts in the package). I will try to update de package version and test again. Thanks for the response
