### ISSUE TITLE
Missing some styles

### ISSUE THREAD

**Issue by Tokenizer94** [VisualSystemsCorp/vsc_quill_delta_to_html#13]
Hi. This is part of my code that converts delta to html:
`
onPressed: () {
  print(_controller.document.toDelta().toJson().map((e) => e as Map<String, dynamic>).toList());
  final converter = QuillDeltaToHtmlConverter(
    _controller.document.toDelta().toJson().map((e) => e as Map<String, dynamic>).toList(),
    ConverterOptions(
      converterOptions: OpConverterOptions(
        classPrefix: '',
        inlineStylesFlag: true,
      ),
      multiLineParagraph: false,
    ),
  );

  final html = converter.convert();
  print(html);
  setState(() {});
},
`

And this is the output of first print:
**[{insert: Line1
I/flutter (27448): }, {insert: Line2, attributes: {color: #FF2196F3}}, {insert: 
I/flutter (27448): }]**

But the output of second print is wrong and has no style with color field:
**<p>Line1</p><p>Line2</p>**

Why is that?

**Comment by dsyrstad** [comment]
The color value (probably generated by `flutter_quill` is not a valid Quill color. `flutter_quill` is creating an 8 digit hex color (ARGB). See 
- https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html/issues/3#issuecomment-1578980271
- https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html/issues/8#issuecomment-1763422239 
- https://github.com/singerdmx/flutter-quill/issues/1257 (the issue reported to Flutter Quill)

There is an open PR for a potential workaround: https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html/pull/11

**Comment by dsyrstad** [comment]
Fixed with PR #16
