### ISSUE TITLE
recognising font size

### ISSUE THREAD

**Issue by LevkoTkach** [VisualSystemsCorp/vsc_quill_delta_to_html#15]
with this delta :
 [{insert: sdfasf}, {insert: d, attributes: {size: 36.0}}, {insert: sdf  , attributes: {size: 30.0}}, {insert: dfasdf, attributes: {size: 36.0}}, {insert: 
flutter: }]
converter return 

`  <p>sdfasfdsdf  dfasdf</p>
`

**Comment by dsyrstad** [comment]
@LevkoTkach By default, `QuillDeltaToHtmlConverter` uses `defaultInlineStyles` (in `op_to_html_converter.dart`) to convert the Quill `size` attribute - this handles the semantic sizes: `small` `large` and `huge`. `defaultInlineStyles` has a map that defines how to convert one of these sizes to a CSS style.

If you want to use a `size` value that is different from `small` `large` or `huge`, you have to define your converter to handle it, like below.

```dart
      converter = QuillDeltaToHtmlConverter(
        delta,
        ConverterOptions(
          converterOptions: OpConverterOptions(
            inlineStylesFlag: true,
            inlineStyles: InlineStyles({
              ...defaultInlineStyles.attrs,
              'size': InlineStyleType(
                fn: (value, _) => 'font-size: ${value}px',
              ),
            }),
          ),
        ),
      );
```

`InlineStyles` takes either a `map` to define an explicit mapping of a value to a CSS style, or a `fn` - like in the example above - which converts an arbitrary value to a CSS style.
