### ISSUE TITLE
Question: how do I force the converted html to al be in a particular font?

### ISSUE THREAD

**Issue by Maarten0110** [VisualSystemsCorp/vsc_quill_delta_to_html#18]
I have set up the quill editor in flutter using the `flutter_quill` package. For my application I want to force a certain font to be used.
I am using `vsc_quill_delta_to_html` to convert the Quill Delta to html to send an email. I tried setting the `inlineStyles` property but it doesn't seem to work.

Code:

```
                  final deltaOps = _controller.document.toDelta().toJson()
                      as List<Map<String, dynamic>>;
                  final converter = QuillDeltaToHtmlConverter(
                    deltaOps,
                    ConverterOptions(
                      converterOptions: OpConverterOptions(
                        inlineStylesFlag: true,
                        inlineStyles: InlineStyles(
                          {
                            "font": InlineStyleType(
                                fn: (_, __) =>
                                    'font-family: Nunito, sans-serif')
                          },
                        ),
                      ),
                      sanitizerOptions: OpAttributeSanitizerOptions(
                          allow8DigitHexColors: true),
                    ),
                  );

                  final html = converter.convert();
                  debugPrint(html);
```

Output (where input is was "**Hello** _world_!"):
```
<p><strong>Hello</strong> <em>world</em>!</p>
```
I would expect something like this:
```
<p style="font-family: 'Nunito', sans-serif;"><strong>Hello</strong> <em>world</em>!</p>
```

Is it possible to do this, and if so, what am I doing wrong? Thanks in advance!

**Comment by dsyrstad** [comment]
@Maarten0110 What does your quill delta json look like (your `deltaOps` above)? Your `inlineStyles` will only have an effect if you specify a `font` attribute in your delta json. If you don't have a `font` attribute, you can wrap the generated HTML in a `<div  style="font-family: 'Nunito', sans-serif;">`.

**Comment by Maarten0110** [comment]
Ah that makes sense! My `deltaOps` indeed does not have a font attribute. Thanks!
