### ISSUE TITLE
html after convert() doesn't have color attribute

### ISSUE THREAD

**Issue by ShijasSoftwareHut** [VisualSystemsCorp/vsc_quill_delta_to_html#19]
this is what I am doing
```
final converter = QuillDeltaToHtmlConverter(List.castFrom(json));
final html = converter.convert();
```
this `json`I am passing to converter 
`[{insert: on, attributes: {color: #FF303F9F}}, {insert:  }, {insert: boarding, attributes: {color: #FFF57F17}}, {insert:  }, {insert: check, attributes: {color: #FFD1155D}}, {insert:  }, {insert: list, attributes: {color: #FFC4F31E}}, {insert:  
}]`
and this is `html `I am getting `<p>on boarding check list </p>` with out any color attribute

**Comment by dsyrstad** [comment]
As mentioned in this issue #3, QuillJS Delta format doesn't support 8 digit hex colors with an alpha component - it only supports 3 or 6 digit. However, there was a PR to this repo that allows you to turn on support for 8 digit hex colors:
 
```dart
      final converter = QuillDeltaToHtmlConverter(
        List.castFrom(json),
        ConverterOptions()..sanitizerOptions.allow8DigitHexColors = true,
      );
```

This is a known problem with `flutter_quill`'s color picker - it always produces quill incompatible 8 digit hex colors.  If you look at the our `example` code, there is an example of  alternative color picker - `simple_color_picker.dart` - which supports 6 digit colors by default, but allows you to create 8 digit colors if you want.
