### ISSUE TITLE
Convert from HTML to Delta with Hex Colour Support?

### ISSUE THREAD

**Issue by JamesAllgood** [VisualSystemsCorp/vsc_quill_delta_to_html#24]
Wondering if someone might be able to point me in the right direction. 

I use this project to export my flutter_quill data to html using the hex colour support using this code 

`    //Convert Quill Text to HTML.
    final deltaOps = _quillController.document.toDelta().toJson();
    final converter = QuillDeltaToHtmlConverter(
      List.castFrom(deltaOps),
      ConverterOptions()..sanitizerOptions.allow8DigitHexColors = true,
    );
    _postText = converter.convert();`

But when I need to reimport it so convert it from html back into delta I'm struggling to convert it back in a delta format where the hex colours work again. 

Currently I reimport my data using this bit of code 

`_quillController.document = Document.fromHtml(Text);`

**Comment by dsyrstad** [comment]
This project doesn't support HTML > Quill, it only performs Quill > HTML. You might want to talk to the `flutter_quill` team.

Our internal project always stores the quill delta in our DB, and only converts to HTML to output it. This way we always deal with deltas and never need to convert HTML back to delta.

**Comment by JamesAllgood** [comment]
no worries thanks!
