### ISSUE TITLE
HTML auto add breakline when document is empty

### ISSUE THREAD

**Issue by Trung15010802** [VisualSystemsCorp/vsc_quill_delta_to_html#26]
![image](https://github.com/user-attachments/assets/e5a1bc5b-069d-4495-8187-0bc7a2a790fb)

**Comment by dsyrstad** [comment]
Can you explain what you want the desired result to be?

**Comment by Trung15010802** [comment]
> Can you explain what you want the desired result to be?

I think it should be empty string

**Comment by dsyrstad** [comment]
The most minimal Quill Delta (https://quilljs.com/docs/delta/#playground) is:
```json
[
  {
    "insert": "\n"
  }
]
```

When converted to HTML, it becomes:
```html
<p><br/></p>
```

If you really want an empty string when the document is "empty", you could do:

```dart
if (quillController.document.isEmpty()) return '';
```

and not call the converter at all.
