### ISSUE TITLE
List items are not converted to HTML

### ISSUE THREAD

**Issue by bloemy7** [VisualSystemsCorp/vsc_quill_delta_to_html#27]
Hi,

First of all thanks for the great work on this package. I'm having an issue though. This is my input delta:

`[{insert: Just testing:, attributes: {indent: 0}}, {insert: 
, attributes: {header: 2}}, {insert: ok, attributes: {list: bullet}}, {insert: 
, attributes: {list: ordered}}]`

This comes directly from the flutter_quill editor.

Here is what it produces:
`<h2>Just testing:</h2><ul><li><br/></li></ul><ol><li><br/></li></ol>`

i.e it correctly sets up a list, but the `ok` text gets lost - it's not put in the sub item, so we end up with an empty bullet.

I'm converting with:
`  final converter = QuillDeltaToHtmlConverter(
    List.castFrom(delta.toJson()),
    ConverterOptions.forEmail(),
  );`

Any idea what is happening here? Thanks.

**Comment by bloemy7** [comment]
Trying to do some debugging here, but basically the list item we end up with is:

`ListItem{item: BlockGroup{op: DeltaInsertOp{insert: InsertDataQuill:{type:
DataType.text, value: ok1}, attributes: {list: bullet, indent: 0}}, ops:
[DeltaInsertOp{insert: InsertDataQuill:{type: DataType.text, value:
}, attributes: {}}]}, innerList: null}`

So the `item.op` is:
`DeltaInsertOp{insert: InsertDataQuill:{type: DataType.text, value: ok1},
attributes: {list: bullet, indent: 0}}`

but the `item.ops` is:
`[DeltaInsertOp{insert: InsertDataQuill:{type: DataType.text, value: 
}, attributes: {}}]`

and since the code uses `item.ops` to extract content, it's empty.
I'm not sure why or what, and again, this delta is generated directly by flutter_quill, so I'm wondering if there is any solution here...

**Comment by bloemy7** [comment]
It gets worse with multiple items in the list:
<img width="188" alt="Screenshot 2024-07-29 at 9 49 32 PM" src="https://github.com/user-attachments/assets/de3ba1b6-a4ae-4605-8111-a451b6760d8f">

This is the delta:
`[{insert: Just testing:, attributes: {indent: 0}}, {insert: 
, attributes: {header: 2}}, {insert: ok1, attributes: {list: bullet}}, {insert: 
, attributes: {list: ordered}}, {insert: test2}, {insert: 
, attributes: {list: ordered}}]`

Yet it renders:
`<h2>Just
testing:</h2><ul><li><br/></li></ul><ol><li><br/></li><li>test2</li></ol>`

**Comment by dsyrstad** [comment]
@bloemy7 This is a `flutter_quill` issue. See our issue #22 for a similar report and discussion. I believe the `flutter_quill` team has fixed the problem in the latest version - see their issue https://github.com/singerdmx/flutter-quill/issues/1940.

**Comment by bloemy7** [comment]
Hi @dsyrstad, thanks a lot. It is indeed fixed in the newest versions of flutter_quill. Thanks!
