### ISSUE TITLE
The styles are being placed in the strong tag

### ISSUE THREAD

**Issue by huanachin** [VisualSystemsCorp/vsc_quill_delta_to_html#28]
`<p>Jesus <strong style="font-size: 2.5em">Huanachin</strong> <strong style="font-size: 2.5em"><em>Carahuanco</em></strong></p>
`
When I try to convert this back to delta it does not recognize the inline styles inside the strong tag

**Comment by dsyrstad** [comment]
@huanachin This project does not handle conversion of html back to delta. You are probably looking for the `flutter_quill` project which does have a package that does that.

**Comment by huanachin** [comment]
I'm sorry I didn't explain well.

When transforming the delta shown below to html, it adds the attributes “font-size”, “color”, etc inside the `<strong styles="font-size=1.5 ..."> ` tag, which is not something recommended. The ideal would be to add these attributes inline inside a new <span> tag.

Delta: 

```
[
  {
    "insert": "Jesus",
    "attributes": {
      "size": "huge",
      "bold": true,
      "italic": true,
      "color": "#FFEF5350",
      "underline": true
    }
  },
  {
    "insert": "\n"
  }
]
```
Result: 

`<p><strong style="color:#EF5350FF;font-size: 2.5em"><em><u>Jesus</u></em></strong></p>`

Expected:

`<p><strong><em><u><span style="color:#EF5350FF;font-size: 2.5em">Jesus</span></u></em></strong></p>`

**Comment by dsyrstad** [comment]
> ...which is not something recommended...

@huanachin Can you provide a reference to this recommendation? As far as I know, this is perfectly acceptable HTML5. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style. The general recommendation is to put styling into CSS, but we cannot here because we are generating a single string of HTML.
