### ISSUE TITLE
Trim content

### ISSUE THREAD

**Issue by loveoverflowdev** [VisualSystemsCorp/vsc_quill_delta_to_html#30]
How can I strip or trim HTML content to remove <br/> tags and whitespace at the beginning and end?

**Comment by dsyrstad** [comment]
@loveoverflowdev There are several ways to manipulate the generated html depending on what you want to do. There are a number of configuration options that can help with this - see `README.md` and https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html/blob/9c4b1ca8306d8772001caa997d7aa8fc0435e677/lib/src/quill_delta_to_html_converter.dart#L16

You can also parse the generated html using 
https://pub.dev/packages/html, manipulate the DOM, and then regenerate the html string.

If you want to add tags or whitespace around the generated html, it is a string, so you can simply add text to it. See  https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html/blob/9c4b1ca8306d8772001caa997d7aa8fc0435e677/example/lib/main.dart#L269 and https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html/blob/9c4b1ca8306d8772001caa997d7aa8fc0435e677/example/lib/main.dart#L309 for examples.

**Comment by loveoverflowdev** [comment]
@dsyrstad 

Thank for your response.

I want to trim whitespace instead of concating space around the contents.

And I did use RegExp, I am not sure if it is good but in some simple case when user typing, the result is acceptable.

Hope you will give me some feedbacks:

```dart
String _htmlEditorResultProvider() {
    final deltaData = _quillEditorController.document.toDelta();

    final converter = QuillDeltaToHtmlConverter(
      deltaData.toJson(),
      ConverterOptions(
        multiLineBlockquote: true,
        multiLineCodeblock: true,
        sanitizerOptions: OpAttributeSanitizerOptions(
          allow8DigitHexColors: true,
        ),
        converterOptions: OpConverterOptions(
          paragraphTag: '',
        ),
      ),
    );

    final html = converter
        .convert()
        .replaceAll(
            RegExp(r'^(<br\s*/?>\s*)+|(\s*<br\s*/?>)+$', caseSensitive: false),
            '')
        .trim();

    print('HTML: $html');
    return html;
  }
```

**Comment by dsyrstad** [comment]
@loveoverflowdev Ah, so by "whitespace", you meant `<br/>` tags. I suppose your regex will work. All `<br/>` tags in the converter are generated using: https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html/blob/9c4b1ca8306d8772001caa997d7aa8fc0435e677/lib/src/quill_delta_to_html_converter.dart#L70

so you could use that const if you want. The `<br/>` tags are being generated corresponding to your quill delta, so if you have extra `\n` inserts in your delta, you'll get corresponding `<br/>` tags in the html to make the equivalent output. You could also try removing the extra `\n`s in your delta, but it depends on your use case.
