### ISSUE TITLE
请问能否将存储的html转换成Delta？

### ISSUE THREAD

**Issue by Quietly-20201113** [VisualSystemsCorp/vsc_quill_delta_to_html#4]
[How to get Delta from a row HTML string in flutter_quill?]

**Comment by dsyrstad** [comment]
> [How to get Delta from a row HTML string in flutter_quill?]

@Quietly-20201113 Could you be more specific? Perhaps include a code sample?

**Comment by Quietly-20201113** [comment]
> > [如何从flutter_quill中的行HTML字符串获取Delta？]
> 
> @Quietly-20201113你可以再详细一点吗？也许包括一个代码示例？

i have a need
Write "message text" in flutter_quill,
1. When saving, it needs to be converted into html to display the "message text" in the pc web,
2. It is also necessary to be able to edit and save the "message text" in pc web,
3. In the flutter APP, the "message text" also needs to be converted from html to Delta format and edited, and it needs to be converted to html when saving

**Comment by dsyrstad** [comment]
@Quietly-20201113 This package only deals with converting Quill Delta format to HTML. It does not convert HTML to Quill. 

You could look at porting a JS library to Dart, such as:
- https://www.npmjs.com/package/node-quill-converter
- https://www.npmjs.com/package/@revolist/quill-html-to-delta

**Comment by Quietly-20201113** [comment]
> @Quietly-20201113该包仅处理将 Quill Delta 格式转换为 HTML。它不会将 HTML 转换为 Quill。
> 
> 您可以考虑将 JS 库移植到 Dart，例如：
> 
> * https://www.npmjs.com/package/node-quill-converter
> * https://www.npmjs.com/package/@revolist/quill-html-to-delta

I need to re-edit in Flutter, so I can't use js, that is, convert Delte to Html in the Flutter APP, and then convert Html to Delte and pass it to Quill for editing

**Comment by dsyrstad** [comment]
> I need to re-edit in Flutter, so I can't use js

I understand. I was suggesting that you convert one of the js packages to Dart, like I did with this package.
