### ISSUE TITLE
Encode space character

### ISSUE THREAD

**Issue by Tokenizer94** [VisualSystemsCorp/vsc_quill_delta_to_html#6]
Hi. Space charcters is not converting to &nbsp;

**Comment by dsyrstad** [comment]
@Tokenizer94 What does your quill json look like and what conversion options are you using?

**Comment by dsyrstad** [comment]
Closing because of no response. If this is still an issue for you, please respond and I will reopen.

**Comment by Tokenizer94** [comment]
> @Tokenizer94 What does your quill json look like and what conversion options are you using?

It does not matter that which conversion options we use. Space characters are ignored and not converted in any situation.

**Comment by dsyrstad** [comment]
@Tokenizer94  If you send me an example of your quill json, I can investigate it.

**Comment by dsyrstad** [comment]
Closing because of no response. If this is still an issue for you, please respond and I will reopen.
