### ISSUE TITLE
Option to add a <p> tag for each new line

### ISSUE THREAD

**Issue by Tokenizer94** [VisualSystemsCorp/vsc_quill_delta_to_html#7]
Hi. I need an option to add a `<p>` tag for each new line. Like this:
`<p>Hi</p>`
`<p>Bye</>`
I am using default conversion options

**Comment by dsyrstad** [comment]
@Tokenizer94 What does your quill json look like and what conversion options are you using? Also, your description doesn't describe what tag you want to add.

**Comment by dsyrstad** [comment]
Closing because of no response. If this is still an issue for you, please respond and I will reopen.

**Comment by Tokenizer94** [comment]
> Closing because of no response. If this is still an issue for you, please respond and I will reopen.

I updated my question. please check again

**Comment by dsyrstad** [comment]
@Tokenizer94 If you use the default converter options, the Quill json:
```json
[
  {
    "insert": "Hi\nBye\n"
  }
]
```

Becomes:
```html5
<p>Hi<br/>Bye</p>
```
If you set `multiLineParagraph` to false, as @gliitterpuke suggested:
```dart
QuillDeltaToHtmlConverter(
      deltaJson,
      ConverterOptions(multiLineParagraph: false),
    );
```
You get your desired result:
```html5
<p>Hi</p><p>Bye</p>
```

Does that work for you?

**Comment by Tokenizer94** [comment]
Thats perfect. Thanks
